Repository astrolabsoftware/fink-spins, pull requests merged in 2023-07, with the labels that each got.

#3 add fink_utils folder and the script to generate the data for the notebooks
  .flake8
  .github/workflows/linter.yml
  .github/workflows/run_test.yml
  fink_utils/README.md
  fink_utils/conftest.py
  fink_utils/generate_data.py
  notebooks/1_merge_results.ipynb
  notebooks/3_validation.ipynb
  notebooks/README.md
  requirements.txt
Labels: enhancement

#5 Issue/4/notebook 3 simplification
  .github/workflows/linter.yml
  .github/workflows/run_test.yml
  README.md
  fink_spins/README.md
  fink_spins/__init__.py
  fink_spins/conftest.py
  fink_spins/generate_data.py
  fink_spins/model.py
  fink_spins/plots.py
  notebooks/3_validation.ipynb
  notebooks/__init__.py
  notebooks/desc_new_phase_model.ipynb
  notebooks/ssptools.py
  setup.py
Labels: enhancement

#10 Update setup for a release
  .gitignore
  setup.py
Labels: release

#6 Automated construction of the SSOFT
  fink_spins/__init__.py
  fink_spins/ssoft.py
  setup.py
Labels: BFT
